# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stat',
            new_name='Status',
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('id',), 'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='stat',
            new_name='status',
        ),
    ]
